In [2]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
import itertools

In [4]:
def apply_component_production(initial_concentration, production_pattern, production_rate, time_step):
    """
    Update the concentration of a species in each cell of a compartment using TensorFlow.

    Parameters:
        - initial_concentration (tf.Tensor): Tensor of initial concentrations for each cell.
        - production_pattern (tf.Tensor): Tensor indicating which cells can produce the species.
        - production_rate (float): Rate at which the species are produced.
        - time_step (float): Discrete time step for the calculation.

    Returns:
        - Updated concentration tensor.
    """

    updated_concentration = tf.maximum(initial_concentration + (production_pattern * production_rate * time_step), 0.0)

    return updated_concentration


In [5]:
def apply_component_production1(initial_concentration, production_pattern, production_rate, time_step):
   
    updated_concentration = np.maximum(initial_concentration + (production_pattern * production_rate * time_step), 0)

    return updated_concentration

In [11]:
t = 0.4
r = 0.6
c = tf.fill(dims=(10, ), value=10.0)
p = tf.fill(dims=(10, ), value=1.3)
c1 = np.full((10, ), fill_value=10.0)
p1 = np.full((10, ), fill_value=1.3)
print(c)
print(p)
print(c1)
print(p1)

tf.Tensor([10. 10. 10. 10. 10. 10. 10. 10. 10. 10.], shape=(10,), dtype=float32)
tf.Tensor([1.3 1.3 1.3 1.3 1.3 1.3 1.3 1.3 1.3 1.3], shape=(10,), dtype=float32)
[10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
[1.3 1.3 1.3 1.3 1.3 1.3 1.3 1.3 1.3 1.3]


In [12]:
np_r = apply_component_production1(c1, p1, r, t)
tf_r = apply_component_production(c, p, r, t)


In [13]:
np_r

array([10.312, 10.312, 10.312, 10.312, 10.312, 10.312, 10.312, 10.312,
       10.312, 10.312])

In [14]:
tf_r

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([10.312, 10.312, 10.312, 10.312, 10.312, 10.312, 10.312, 10.312,
       10.312, 10.312], dtype=float32)>

In [15]:
def apply_component_degradation(initial_concentration, degradation_rate, time_step):
    """
    Apply degradation to the concentration of a species over time.

    Parameters:
    - initial_concentration (1d array): Array of initial concentrations for each cell.
    - degradation_rate (float): Rate at which the species degrades.
    - time_step (float): Discrete time step for the calculation.

    Returns:
    - Updated concentrations after applying degradation.
    """
    updated_concentration = np.maximum(initial_concentration - (initial_concentration * degradation_rate * time_step), 0)

    return updated_concentration

In [16]:
def apply_component_degradation1(initial_concentration, degradation_rate, time_step):
    """
    Apply degradation to the concentration of a species over time.

    Parameters:
    - initial_concentration (1d array): Array of initial concentrations for each cell.
    - degradation_rate (float): Rate at which the species degrades.
    - time_step (float): Discrete time step for the calculation.

    Returns:
    - Updated concentrations after applying degradation.
    """
    updated_concentration = tf.maximum(initial_concentration - (initial_concentration * degradation_rate * time_step), 0)

    return updated_concentration

In [21]:
np_deg = apply_component_degradation(c, 0.8, 0.01)
tf_deg = apply_component_degradation1(c1, 0.8, 0.01)

In [22]:
np_deg

array([9.92, 9.92, 9.92, 9.92, 9.92, 9.92, 9.92, 9.92, 9.92, 9.92],
      dtype=float32)

In [23]:
tf_deg

<tf.Tensor: shape=(10,), dtype=float64, numpy=array([9.92, 9.92, 9.92, 9.92, 9.92, 9.92, 9.92, 9.92, 9.92, 9.92])>

In [24]:
def apply_species_collision(species1, species2, complex_, collision_rate, time_step):
    """
    Apply the effect of species collision to form a complex and update the concentrations of the species.

    Parameters:
    - species1 (1d array): Array of concentrations of the first species.
    - species2 (1d array): Array of concentrations of the second species.
    - complex_ (1d array): Array of current concentrations of the complex.
    - collision_rate (float): Rate at which collisions occur between the two species.
    - time_step (float): Discrete time step  for the calculation.

    Returns:
    - tuple of numpy.ndarray: Updated concentrations of both species and the total amount of complex formed.
    """
    collision_effect = collision_rate * time_step
    complex_formed = np.minimum(species1 * collision_effect, species2 * collision_effect)
    complex_formed = np.maximum(complex_formed, 0)

    updated_species1 = np.maximum(species1 - complex_formed, 0)
    updated_species2 = np.maximum(species2 - complex_formed, 0)

    updated_complex = complex_ + complex_formed

    return updated_species1, updated_species2, updated_complex

In [25]:
def apply_species_collision1(species1, species2, complex_, collision_rate, time_step):
    """
    Apply the effect of species collision to form a complex and update the concentrations of the species.

    Parameters:
    - species1 (1d array): Array of concentrations of the first species.
    - species2 (1d array): Array of concentrations of the second species.
    - complex_ (1d array): Array of current concentrations of the complex.
    - collision_rate (float): Rate at which collisions occur between the two species.
    - time_step (float): Discrete time step  for the calculation.

    Returns:
    - tuple of numpy.ndarray: Updated concentrations of both species and the total amount of complex formed.
    """
    collision_effect = collision_rate * time_step
    complex_formed =tf.minimum(species1 * collision_effect, species2 * collision_effect)
    complex_formed = tf.maximum(complex_formed, 0)

    updated_species1 = tf.maximum(species1 - complex_formed, 0)
    updated_species2 = tf.maximum(species2 - complex_formed, 0)

    updated_complex = complex_ + complex_formed

    return updated_species1, updated_species2, updated_complex

In [26]:
sp1 = tf.fill(dims=(10, ), value=10.0)
sp2 = tf.fill(dims=(10, ), value=2.0)
comp = tf.fill(dims=(10, ), value=12.0)

sp11 = np.full((10, ), fill_value=10.0)
sp21 = np.full((10, ), fill_value=2.0)
comp1 = np.full((10, ), fill_value=12.0)
print(sp1)
print(sp2)
print(comp)
print(sp11)
print(sp21)
print(comp1)

tf.Tensor([10. 10. 10. 10. 10. 10. 10. 10. 10. 10.], shape=(10,), dtype=float32)
tf.Tensor([2. 2. 2. 2. 2. 2. 2. 2. 2. 2.], shape=(10,), dtype=float32)
tf.Tensor([12. 12. 12. 12. 12. 12. 12. 12. 12. 12.], shape=(10,), dtype=float32)
[10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
[2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
[12. 12. 12. 12. 12. 12. 12. 12. 12. 12.]


In [29]:
np_sp1, np_sp2, np_comp = apply_species_collision(sp11, sp21, comp1, 0.2, 0.1)
tf_sp1, tf_sp2, tf_comp = apply_species_collision1(sp1, sp2, comp, 0.2, 0.1)

In [30]:
np_sp1

array([9.96, 9.96, 9.96, 9.96, 9.96, 9.96, 9.96, 9.96, 9.96, 9.96])

In [31]:
np_sp2

array([1.96, 1.96, 1.96, 1.96, 1.96, 1.96, 1.96, 1.96, 1.96, 1.96])

In [32]:
np_comp

array([12.04, 12.04, 12.04, 12.04, 12.04, 12.04, 12.04, 12.04, 12.04,
       12.04])

In [33]:
tf_sp1

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([9.96, 9.96, 9.96, 9.96, 9.96, 9.96, 9.96, 9.96, 9.96, 9.96],
      dtype=float32)>

In [34]:
tf_sp2

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([1.96, 1.96, 1.96, 1.96, 1.96, 1.96, 1.96, 1.96, 1.96, 1.96],
      dtype=float32)>

In [35]:
tf_comp

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([12.04, 12.04, 12.04, 12.04, 12.04, 12.04, 12.04, 12.04, 12.04,
       12.04], dtype=float32)>

In [36]:
def apply_complex_dissociation(species1, species2, complex_, dissociation_rate, time_step):
    """
    Apply the effect of complex dissociation to update the concentrations of the two species and the complex of them.

    Parameters:
    - species1 (tf.Tensor): Tensor of concentrations of the first species.
    - species2 (tf.Tensor): Tensor of concentrations of the second species.
    - complex_ (tf.Tensor): Tensor of current concentrations of the complex.
    - dissociation_rate (float): Rate at which the complex dissociates into the two species.
    - time_step (float): Discrete time step for the calculation.

    Returns:
    - tuple of numpy.ndarray: Updated concentrations of both species and the remaining amount of the complex.
    """
    dissociation_effect = dissociation_rate * time_step
    dissociated_amount = complex_ * dissociation_effect
    dissociated_amount = np.maximum(dissociated_amount, 0)

    updated_complex = np.maximum(complex_ - dissociated_amount, 0)
    updated_species1 = np.maximum(species1 + dissociated_amount, 0)
    updated_species2 = np.maximum(species2 + dissociated_amount, 0)

    return updated_species1, updated_species2, updated_complex

In [38]:
def apply_complex_dissociation1(species1, species2, complex_, dissociation_rate, time_step):
    """
    Apply the effect of complex dissociation to update the concentrations of the two species and the complex of them.

    Parameters:
    - species1 (tf.Tensor): Tensor of concentrations of the first species.
    - species2 (tf.Tensor): Tensor of concentrations of the second species.
    - complex_ (tf.Tensor): Tensor of current concentrations of the complex.
    - dissociation_rate (float): Rate at which the complex dissociates into the two species.
    - time_step (float): Discrete time step for the calculation.

    Returns:
    - tuple of numpy.ndarray: Updated concentrations of both species and the remaining amount of the complex.
    """
    dissociation_effect = dissociation_rate * time_step
    dissociated_amount = complex_ * dissociation_effect
    dissociated_amount = tf.maximum(dissociated_amount, 0)

    updated_complex = tf.maximum(complex_ - dissociated_amount, 0)
    updated_species1 = tf.maximum(species1 + dissociated_amount, 0)
    updated_species2 = tf.maximum(species2 + dissociated_amount, 0)

    return updated_species1, updated_species2, updated_complex

In [39]:
np_sp1, np_sp2, np_comp = apply_complex_dissociation(sp11, sp21, comp1, 0.5, 0.4)
tf_sp1, tf_sp2, tf_comp = apply_complex_dissociation(sp1, sp2, comp, 0.5, 0.4)

In [40]:
np_sp1

array([12.4, 12.4, 12.4, 12.4, 12.4, 12.4, 12.4, 12.4, 12.4, 12.4])

In [41]:
np_sp2

array([4.4, 4.4, 4.4, 4.4, 4.4, 4.4, 4.4, 4.4, 4.4, 4.4])

In [42]:
np_comp

array([9.6, 9.6, 9.6, 9.6, 9.6, 9.6, 9.6, 9.6, 9.6, 9.6])

In [43]:
tf_sp1

array([12.4, 12.4, 12.4, 12.4, 12.4, 12.4, 12.4, 12.4, 12.4, 12.4],
      dtype=float32)

In [44]:
tf_sp2

array([4.4, 4.4, 4.4, 4.4, 4.4, 4.4, 4.4, 4.4, 4.4, 4.4], dtype=float32)

In [45]:
tf_comp

array([9.6, 9.6, 9.6, 9.6, 9.6, 9.6, 9.6, 9.6, 9.6, 9.6], dtype=float32)

In [91]:
def apply_diffusion(current_concentration, compartment, column_position, diffusion_rate, time_step):
    """
    Apply diffusion to update the concentration of species in a specific column of a 2D compartment for all individual in population.

    Parameters:
    - current_concentration (2d array): Array of current concentrations for each cell.
    - compartment (3d array): Array representing the 2D compartment where diffusion takes place for all individual in population.
    - column_position (int): Column position of the cells being updated (0-based index).
    - diffusion_rates (1d array): Rates at which the species diffuses between cells.
    - time_step (float/1d array): Discrete time step/s for the calculation.

    Returns:
    - 2d array: updated current_concentration array.
    """
    compartment_size = compartment.shape[1]
    temporary_concentration = np.copy(current_concentration)

    if column_position == 0:

        # Update concentration for the upper-left corner cell
        temporary_concentration[0] = update_upper_left_corner_concentration(
            cell_concentration=current_concentration[0],
            lower_cell_concentration=compartment[1, 0],
            right_cell_concentration=compartment[0, 1],
            diffusion_rate=diffusion_rate,
            time_step=time_step
        )

        # Update concentration for the lower-left corner cell
        temporary_concentration[-1] = update_lower_left_corner_concentration(
            cell_concentration=current_concentration[-1],
            upper_cell_concentration=compartment[-2, 0],
            right_cell_concentration=compartment[-1, 1],
            diffusion_rate=diffusion_rate,
            time_step=time_step
        )

        # Update concentrations for the left-side cells (excluding corners)
        temporary_concentration[1:-1] = update_left_side_concentration(
            cell_concentration=current_concentration[1:-1],
            upper_cell_concentration=compartment[:-2, 0],
            lower_cell_concentration=compartment[2:, 0],
            right_cell_concentration=compartment[1:-1, 1],
            diffusion_rate=diffusion_rate,
            time_step=time_step
        )

    elif column_position == compartment_size - 1:

        # Update concentration for the upper-right corner cell
        temporary_concentration[0] = update_upper_right_corner_concentration(
            cell_concentration=current_concentration[0],
            lower_cell_concentration=compartment[1, -1],
            left_cell_concentration=compartment[0, -2],
            diffusion_rate=diffusion_rate,
            time_step=time_step
        )

        # Update concentration for the lower-right corner cell
        temporary_concentration[-1] = update_lower_right_corner_concentration(
            cell_concentration=current_concentration[-1],
            upper_cell_concentration=compartment[-2, -1],
            left_cell_concentration=compartment[-1, -2],
            diffusion_rate=diffusion_rate,
            time_step=time_step
        )

        # Update concentrations for the left-side cells (excluding corners)
        temporary_concentration[1:-1] = update_right_side_concentration(
            cell_concentration=current_concentration[1:-1],
            upper_cell_concentration=compartment[0:-2, -1],
            lower_cell_concentration=compartment[2:, -1],
            left_cell_concentration=compartment[1:-1, -2],
            diffusion_rate=diffusion_rate,
            time_step=time_step
        )


    else:

        temporary_concentration[0] = update_central_concentration_upper(
            cell_concentration=current_concentration[0],
            lower_cell_concentration=compartment[1, column_position],
            right_cell_concentration=compartment[0, column_position + 1],
            left_cell_concentration=compartment[0, column_position - 1],
            diffusion_rate=diffusion_rate,
            time_step=time_step)

        temporary_concentration[-1] = update_central_concentration_lower(
            cell_concentration=current_concentration[-1],
            upper_cell_concentration=compartment[-2, column_position],
            right_cell_concentration=compartment[-1, column_position + 1],
            left_cell_concentration=compartment[-1, column_position - 1],
            diffusion_rate=diffusion_rate,
            time_step=time_step)

        temporary_concentration[1:-1] = update_central_concentration_middle(
            cell_concentration=current_concentration[1:-1],
            upper_cell_concentration=compartment[0:-2, column_position],
            lower_cell_concentration=compartment[2:, column_position],
            right_cell_concentration=compartment[1:-1, column_position+1],
            left_cell_concentration=compartment[1:-1, column_position-1],
            diffusion_rate=diffusion_rate,
            time_step=time_step
        )

    updated_concentration = np.maximum(temporary_concentration, 0)

    return updated_concentration




def update_lower_left_corner_concentration(
    cell_concentration,
    upper_cell_concentration,
    right_cell_concentration,
    diffusion_rate,
    time_step):

    
    in_diffusion = (time_step * upper_cell_concentration * diffusion_rate) + \
                   (time_step * right_cell_concentration * diffusion_rate)
    out_diffusion = time_step * cell_concentration * diffusion_rate * 2

    updated_concentration = cell_concentration + in_diffusion - out_diffusion

    return updated_concentration



def update_lower_right_corner_concentration(
    cell_concentration,
    upper_cell_concentration,
    left_cell_concentration,
    diffusion_rate,
    time_step):

    
    in_diffusion = (time_step * upper_cell_concentration * diffusion_rate) + \
                   (time_step * left_cell_concentration * diffusion_rate)
    out_diffusion = time_step * cell_concentration * diffusion_rate * 2

    updated_concentration = cell_concentration + in_diffusion - out_diffusion

    return updated_concentration



def update_upper_left_corner_concentration(
    cell_concentration,
    lower_cell_concentration,
    right_cell_concentration,
    diffusion_rate,
    time_step):

    
    in_diffusion = (time_step * lower_cell_concentration * diffusion_rate) + \
                   (time_step * right_cell_concentration * diffusion_rate)
    out_diffusion = time_step * cell_concentration * diffusion_rate * 2

    updated_concentration = cell_concentration + in_diffusion - out_diffusion

    return updated_concentration



def update_upper_right_corner_concentration(
    cell_concentration,
    lower_cell_concentration,
    left_cell_concentration,
    diffusion_rate,
    time_step):

    
    in_diffusion = (time_step * lower_cell_concentration * diffusion_rate) + \
                   (time_step * left_cell_concentration * diffusion_rate)
    out_diffusion = time_step * cell_concentration * diffusion_rate * 2

    updated_concentration = cell_concentration + in_diffusion - out_diffusion

    return updated_concentration


def update_left_side_concentration(
    cell_concentration,
    upper_cell_concentration,
    lower_cell_concentration,
    right_cell_concentration,
    diffusion_rate,
    time_step):

    upper_cell_in = time_step * upper_cell_concentration * diffusion_rate
    lower_cell_in = time_step * lower_cell_concentration * diffusion_rate
    right_cell_in = time_step * right_cell_concentration * diffusion_rate

    in_diffusion = upper_cell_in + lower_cell_in + right_cell_in
    out_diffusion = time_step * cell_concentration * diffusion_rate * 3

    updated_concentration = cell_concentration + in_diffusion - out_diffusion

    return updated_concentration



def update_right_side_concentration(
        cell_concentration,
        upper_cell_concentration,
        lower_cell_concentration,
        left_cell_concentration,
        diffusion_rate,
        time_step):
 
    upper_cell_in = time_step * upper_cell_concentration * diffusion_rate
    lower_cell_in = time_step * lower_cell_concentration * diffusion_rate
    right_cell_in = time_step * left_cell_concentration * diffusion_rate

    in_diffusion = upper_cell_in + lower_cell_in + right_cell_in
    out_diffusion = time_step * cell_concentration.T * diffusion_rate * 3

    updated_concentration = cell_concentration + in_diffusion - out_diffusion

    return updated_concentration


def update_central_concentration_middle(
        cell_concentration,
        upper_cell_concentration,
        lower_cell_concentration,
        right_cell_concentration,
        left_cell_concentration,
        diffusion_rate,
        time_step):
 
    upper_cell_in = time_step * upper_cell_concentration * diffusion_rate
    lower_cell_in = time_step * lower_cell_concentration * diffusion_rate
    right_cell_in = time_step * right_cell_concentration * diffusion_rate
    left_cell_in = time_step * left_cell_concentration * diffusion_rate

    in_diffusion = upper_cell_in + lower_cell_in + right_cell_in + left_cell_in
    out_diffusion = time_step * cell_concentration * diffusion_rate * 4

    updated_concentration = cell_concentration + in_diffusion - out_diffusion

    return updated_concentration



def update_central_concentration_upper(
        cell_concentration,
        lower_cell_concentration,
        right_cell_concentration,
        left_cell_concentration,
        diffusion_rate,
        time_step):
 
    lower_cell_in = time_step * lower_cell_concentration * diffusion_rate
    right_cell_in = time_step * right_cell_concentration * diffusion_rate
    left_cell_in = time_step * left_cell_concentration * diffusion_rate

    in_diffusion = lower_cell_in + right_cell_in + left_cell_in
    out_diffusion = time_step * cell_concentration * diffusion_rate * 3

    updated_concentration = cell_concentration + in_diffusion - out_diffusion

    return updated_concentration


def update_central_concentration_lower(
        cell_concentration,
        upper_cell_concentration,
        right_cell_concentration,
        left_cell_concentration,
        diffusion_rate,
        time_step):
  
    upper_cell_in = time_step * upper_cell_concentration * diffusion_rate
    right_cell_in = time_step * right_cell_concentration * diffusion_rate
    left_cell_in = time_step * left_cell_concentration * diffusion_rate

    in_diffusion = upper_cell_in + right_cell_in + left_cell_in
    out_diffusion = time_step * cell_concentration * diffusion_rate * 3

    updated_concentration = cell_concentration + in_diffusion - out_diffusion

    return updated_concentration

In [99]:
import tensorflow as tf

def apply_diffusion1(current_concentration, compartment, column_position, diffusion_rate, time_step):
    """
    Apply diffusion to update the concentration of species in a specific column of a 2D compartment.

    Parameters:
        - current_concentration (1d tensor): Tensor of current concentrations for each cell of the column.
        - compartment (2d tensor): Tensor representing the 2D compartment where diffusion takes place.
        - column_position (int): Column position of the cells being updated (0-based index).
        - diffusion_rate (float): Rate at which the species diffuses between cells.
        - time_step (float): Discrete time step for the calculation.

    Returns:
        - 1d tensor: updated current_concentration tensor.
    """
    compartment_size = compartment.shape[0]
    temporary_concentration = tf.identity(current_concentration)

    indices = []

    # Update corner and side cells
    if column_position == 0:
        indices = [[0], [-1]] + [[i] for i in range(1, compartment_size - 1)]
        updates = tf.concat([
            update_upper_left_corner_concentration(
                cell_concentration=current_concentration[0],
                lower_cell_concentration=compartment[1, 0],
                right_cell_concentration=compartment[0, 1],
                diffusion_rate=diffusion_rate,
                time_step=time_step
            ),
            update_lower_left_corner_concentration(
                cell_concentration=current_concentration[-1],
                upper_cell_concentration=compartment[-2, 0],
                right_cell_concentration=compartment[-1, 1],
                diffusion_rate=diffusion_rate,
                time_step=time_step
            ),
            update_left_side_concentration(
                cell_concentration=current_concentration[1:-1],
                upper_cell_concentration=compartment[:-2, 0],
                lower_cell_concentration=compartment[2:, 0],
                right_cell_concentration=compartment[1:-1, 1],
                diffusion_rate=diffusion_rate,
                time_step=time_step
            )
        ], axis=0)
    
    elif column_position == compartment_size - 1:
        indices = [[0], [-1]] + [[i] for i in range(1, compartment_size - 1)]
        updates = tf.concat([
            update_upper_right_corner_concentration(
                cell_concentration=current_concentration[0],
                lower_cell_concentration=compartment[1, -1],
                left_cell_concentration=compartment[0, -2],
                diffusion_rate=diffusion_rate,
                time_step=time_step
            ),
            update_lower_right_corner_concentration(
                cell_concentration=current_concentration[-1],
                upper_cell_concentration=compartment[-2, -1],
                left_cell_concentration=compartment[-1, -2],
                diffusion_rate=diffusion_rate,
                time_step=time_step
            ),
            update_right_side_concentration(
                cell_concentration=current_concentration[1:-1],
                upper_cell_concentration=compartment[:-2, -1],
                lower_cell_concentration=compartment[2:, -1],
                left_cell_concentration=compartment[1:-1, -2],
                diffusion_rate=diffusion_rate,
                time_step=time_step
            )
        ], axis=0)
    
    else:
        indices = [[0], [-1]] + [[i] for i in range(1, compartment_size - 1)]
        updates = tf.concat([
            update_central_concentration_upper(
                cell_concentration=current_concentration[0],
                lower_cell_concentration=compartment[1, column_position],
                right_cell_concentration=compartment[0, column_position + 1],
                left_cell_concentration=compartment[0, column_position - 1],
                diffusion_rate=diffusion_rate,
                time_step=time_step
            ),
            update_central_concentration_lower(
                cell_concentration=current_concentration[-1],
                upper_cell_concentration=compartment[-2, column_position],
                right_cell_concentration=compartment[-1, column_position + 1],
                left_cell_concentration=compartment[-1, column_position - 1],
                diffusion_rate=diffusion_rate,
                time_step=time_step
            ),
            update_central_concentration_middle(
                cell_concentration=current_concentration[1:-1],
                upper_cell_concentration=compartment[0:-2, column_position],
                lower_cell_concentration=compartment[2:, column_position],
                right_cell_concentration=compartment[1:-1, column_position + 1],
                left_cell_concentration=compartment[1:-1, column_position - 1],
                diffusion_rate=diffusion_rate,
                time_step=time_step
            )
        ], axis=0)

    temporary_concentration = tf.tensor_scatter_nd_update(temporary_concentration, tf.constant(indices), updates)
    updated_concentration = tf.maximum(temporary_concentration, 0.0)

    return updated_concentration


def update_lower_left_corner_concentration(
    cell_concentration,
    upper_cell_concentration,
    right_cell_concentration,
    diffusion_rate,
    time_step
):
    """
    Update the concentration of a species in a cell located at the lower-left corner of a 2D compartment
    based on diffusion from neighboring cells.

    Parameters:
    - cell_concentration (1d array): Concentration of the species in the lower-left corner cell.
    - upper_cell_concentration (1d array): Concentration of the species in the cell directly above the lower-left cell.
    - right_cell_concentration (1d array): Concentration of the species in the cell directly to the right of the lower-left cell.
    - diffusion_rate (float): Rate at which the species diffuses between cells.
    - time_step (float): Discrete time step for the calculation.

    Returns:
    - 1d array: Updated concentration of the species in the lower-left corner cell.
    """
    in_diffusion = (time_step * upper_cell_concentration * diffusion_rate) + \
                   (time_step * right_cell_concentration * diffusion_rate)
    out_diffusion = time_step * cell_concentration * diffusion_rate * 2

    updated_concentration = cell_concentration + in_diffusion - out_diffusion

    return updated_concentration



def update_lower_right_corner_concentration(
    cell_concentration,
    upper_cell_concentration,
    left_cell_concentration,
    diffusion_rate,
    time_step
):
    """
        Update the concentration of a species in a cell located at the lower-right corner of a 2D compartment
        based on diffusion from neighboring cells.

        Parameters:
        - cell_concentration (1d array): Concentration of the species in the lower-left corner cell.
        - upper_cell_concentration (1d array): Concentration of the species in the cell directly above the lower-right cell.
        - left_cell_concentration (1d array): Concentration of the species in the cell directly to the left of the lower-right cell.
        - diffusion_rate (float): Rate at which the species diffuses between cells.
        - time_step (float): Discrete time step for the calculation.

        Returns:
        - 1d array: Updated concentration of the species in the lower-left corner cell.
        """
    in_diffusion = (time_step * upper_cell_concentration * diffusion_rate) + \
                   (time_step * left_cell_concentration * diffusion_rate)
    out_diffusion = time_step * cell_concentration * diffusion_rate * 2

    updated_concentration = cell_concentration + in_diffusion - out_diffusion

    return updated_concentration



def update_upper_left_corner_concentration(
    cell_concentration,
    lower_cell_concentration,
    right_cell_concentration,
    diffusion_rate,
    time_step
):
    """
    Update the concentration of a species in a cell located at the upper-left corner of a 2D compartment
    based on diffusion from neighboring cells for each individual in population.

    Parameters:
    - cell_concentration (1d array): Concentration of the species in the upper-left corner cell.
    - lower_cell_concentration (1d array): Concentration of the species in the cell directly below the upper-left cell.
    - right_cell_concentration (1d array): Concentration of the species in the cell directly to the right of the upper-left cell.
    - diffusion_rate (float): Rates at which the species diffuses between cells.
    - time_step (float): Discrete time step for the calculation.

    Returns:
    - 1d array: Updated concentration of the species in the upper-left corner cell.
    """
    in_diffusion = (time_step * lower_cell_concentration * diffusion_rate) + \
                   (time_step * right_cell_concentration * diffusion_rate)
    out_diffusion = time_step * cell_concentration * diffusion_rate * 2

    updated_concentration = cell_concentration + in_diffusion - out_diffusion

    return updated_concentration



def update_upper_right_corner_concentration(
    cell_concentration,
    lower_cell_concentration,
    left_cell_concentration,
    diffusion_rate,
    time_step
):
    """
        Update the concentration of a species in a cell located at the upper-right corner of a 2D compartment
        based on diffusion from neighboring cells.

        Parameters:
        - cell_concentration (1d array): Concentration of the species in the upper-right corner cell.
        - lower_cell_concentration (1d array): Concentration of the species in the cell directly below the upper-left cell.
        - left_cell_concentration (1d array): Concentration of the species in the cell directly to the left of the upper-right cell.
        - diffusion_rate (float): Rate at which the species diffuses between cells.
        - time_step (float/1d array): Discrete time step/s for the calculation.

        Returns:
        - 1d array: Updated concentration of the species in the upper-left corner cell.
        """
    in_diffusion = (time_step * lower_cell_concentration * diffusion_rate) + \
                   (time_step * left_cell_concentration * diffusion_rate)
    out_diffusion = time_step * cell_concentration * diffusion_rate * 2

    updated_concentration = cell_concentration + in_diffusion - out_diffusion

    return updated_concentration




def update_left_side_concentration(
    cell_concentration,
    upper_cell_concentration,
    lower_cell_concentration,
    right_cell_concentration,
    diffusion_rate,
    time_step
):
    """
    Update the concentration of a species in cells located along the left side of a 2D compartment
    (excluding the corners) based on diffusion from neighboring cells for each individual in population.

    Parameters:
    - cell_concentration (2d array): Array of concentrations for cells in the leftmost column (excluding corners).
    - upper_cell_concentration (2d array): Array of concentrations for cells directly above the current cells.
    - lower_cell_concentration (2d array): Array of concentrations for cells directly below the current cells.
    - right_cell_concentration (2d array): Array of concentrations for cells directly to the right of the current cells.
    - diffusion_rate (float): Rate at which the species diffuses between cells.
    - time_step (float): Discrete time step for the calculation.

    Returns:
    - numpy.ndarray: Updated concentrations of the species in the current cells.
    """
    upper_cell_in = time_step * upper_cell_concentration * diffusion_rate
    lower_cell_in = time_step * lower_cell_concentration * diffusion_rate
    right_cell_in = time_step * right_cell_concentration * diffusion_rate

    in_diffusion = upper_cell_in + lower_cell_in + right_cell_in
    out_diffusion = time_step * cell_concentration * diffusion_rate * 3

    updated_concentration = cell_concentration + in_diffusion - out_diffusion

    return updated_concentration




def update_right_side_concentration(
        cell_concentration,
        upper_cell_concentration,
        lower_cell_concentration,
        left_cell_concentration,
        diffusion_rate,
        time_step
):
    """
        Update the concentration of a species in cells located along the right side of a 2D compartment
        (excluding the corners) based on diffusion from neighboring cells for each individual in population.

        Parameters:
        - cell_concentration (2d array): Array of concentrations for cells in the leftmost column (excluding corners).
        - upper_cell_concentration (2d array): Array of concentrations for cells directly above the current cells.
        - lower_cell_concentration (2d array): Array of concentrations for cells directly below the current cells.
        - left_cell_concentration (2d array): Array of concentrations for cells directly to the left of the current cells.
        - diffusion_rate (float): Rate at which the species diffuses between cells.
        - time_step (float): Discrete time step for the calculation.

        Returns:
        - numpy.ndarray: Updated concentrations of the species in the current cells.
        """
    upper_cell_in = time_step * upper_cell_concentration * diffusion_rate
    lower_cell_in = time_step * lower_cell_concentration * diffusion_rate
    right_cell_in = time_step * left_cell_concentration * diffusion_rate

    in_diffusion = upper_cell_in + lower_cell_in + right_cell_in
    out_diffusion = time_step * cell_concentration.T * diffusion_rate * 3

    updated_concentration = cell_concentration + in_diffusion - out_diffusion

    return updated_concentration



def update_central_concentration_middle(
        cell_concentration,
        upper_cell_concentration,
        lower_cell_concentration,
        right_cell_concentration,
        left_cell_concentration,
        diffusion_rate,
        time_step
):
    """
    Update the concentration of species in multiple interior cells of a 2D compartment based on diffusion
    from neighboring cells for each individual in population.

    Parameters:
    - cell_concentration (2d array): Array of concentrations for multiple interior cells.
    - upper_cell_concentration (2d array): Array of concentrations for the cells directly above the current cells.
    - lower_cell_concentration (2d array): Array of concentrations for the cells directly below the current cells.
    - right_cell_concentration (2d array): Array of concentrations for the cells directly to the right of the current cells.
    - left_cell_concentration (2d array): Array of concentrations for the cells directly to the left of the current cells.
    - diffusion_rate (float): Rate at which the species diffuses between cells.
    - time_step (float): Discrete time step for the calculation.

    Returns:
    - ndarray: Updated concentrations of the species in the current interior cells.
    """
    upper_cell_in = time_step * upper_cell_concentration * diffusion_rate
    lower_cell_in = time_step * lower_cell_concentration * diffusion_rate
    right_cell_in = time_step * right_cell_concentration * diffusion_rate
    left_cell_in = time_step * left_cell_concentration * diffusion_rate

    in_diffusion = upper_cell_in + lower_cell_in + right_cell_in + left_cell_in
    out_diffusion = time_step * cell_concentration * diffusion_rate * 4

    updated_concentration = cell_concentration + in_diffusion - out_diffusion

    return updated_concentration



def update_central_concentration_upper(
        cell_concentration,
        lower_cell_concentration,
        right_cell_concentration,
        left_cell_concentration,
        diffusion_rate,
        time_step
):
    """
    Update the concentration of a species in a cell located in the upper interior of a 2D compartment
    based on diffusion from neighboring cells for each individual in population.

    Parameters:
    - cell_concentration (1d array): Concentration of the species in the current upper interior cell.
    - lower_cell_concentration (1d array): Concentration of the species in the cell directly below the current cell.
    - right_cell_concentration (1d array): Concentration of the species in the cell directly to the right of the current cell.
    - left_cell_concentration (1d array): Concentration of the species in the cell directly to the left of the current cell.
    - diffusion_rate (float): Rate at which the species diffuses between cells.
    - time_step (float): Discrete time step for the calculation.

    Returns:
    - 1d array: Updated concentration of the species in the current upper interior cell.
    """
    lower_cell_in = time_step * lower_cell_concentration * diffusion_rate
    right_cell_in = time_step * right_cell_concentration * diffusion_rate
    left_cell_in = time_step * left_cell_concentration * diffusion_rate

    in_diffusion = lower_cell_in + right_cell_in + left_cell_in
    out_diffusion = time_step * cell_concentration * diffusion_rate * 3

    updated_concentration = cell_concentration + in_diffusion - out_diffusion

    return updated_concentration




def update_central_concentration_lower(
        cell_concentration,
        upper_cell_concentration,
        right_cell_concentration,
        left_cell_concentration,
        diffusion_rate,
        time_step
):
    """
    Update the concentration of a species in a cell located in the lower interior of a 2D compartment
    based on diffusion from neighboring cells.

    Parameters:
    - cell_concentration (1d array): Concentration of the species in the current lower interior cell.
    - upper_cell_concentration (1d array): Concentration of the species in the cell directly above the current cell.
    - right_cell_concentration (1d array): Concentration of the species in the cell directly to the right of the current cell.
    - left_cell_concentration (1d array): Concentration of the species in the cell directly to the left of the current cell.
    - diffusion_rate (float): Rate at which the species diffuses between cells.
    - time_step (float): Discrete time step for the calculation.

    Returns:
    - 1d array: Updated concentration of the species in the current lower interior cell.
    """
    upper_cell_in = time_step * upper_cell_concentration * diffusion_rate
    right_cell_in = time_step * right_cell_concentration * diffusion_rate
    left_cell_in = time_step * left_cell_concentration * diffusion_rate

    in_diffusion = upper_cell_in + right_cell_in + left_cell_in
    out_diffusion = time_step * cell_concentration * diffusion_rate * 3

    updated_concentration = cell_concentration + in_diffusion - out_diffusion

    return updated_concentration

In [100]:
#c = np.full((10, ), fill_value=10.0)
c1 = tf.fill((10, ), value=10.0)
#com = np.full((10, 10), fill_value=0.0)
com = tf.fill((10, 10), value=0.0)

indices = tf.constant([[i, j] for i in range(10) for j in range(5, 7)])
updates = tf.constant([2.0] * 20)
com1 = tf.tensor_scatter_nd_update(com, indices, updates)

h = apply_diffusion1(c1, com1, 5, 0.9, 0.1)
h

2024-08-26 18:17:39.942461: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: INVALID_ARGUMENT: ConcatOp : Can't concatenate scalars (use tf.stack instead)


InvalidArgumentError: {{function_node __wrapped__ConcatV2_N_3_device_/job:localhost/replica:0/task:0/device:CPU:0}} ConcatOp : Can't concatenate scalars (use tf.stack instead) [Op:ConcatV2] name: concat

In [61]:
def update_lower_left_corner_concentration(
    cell_concentration,
    upper_cell_concentration,
    right_cell_concentration,
    diffusion_rate,
    time_step):
    """
    Update the concentration of a species in a cell located at the lower-left corner of a 2D compartment
    based on diffusion from neighboring cells.

    Parameters:
    - cell_concentration (1d array): Concentration of the species in the lower-left corner cell.
    - upper_cell_concentration (1d array): Concentration of the species in the cell directly above the lower-left cell.
    - right_cell_concentration (1d array): Concentration of the species in the cell directly to the right of the lower-left cell.
    - diffusion_rate (float): Rate at which the species diffuses between cells.
    - time_step (float): Discrete time step for the calculation.

    Returns:
    - 1d array: Updated concentration of the species in the lower-left corner cell.
    """
    in_diffusion = (time_step * upper_cell_concentration * diffusion_rate) + \
                   (time_step * right_cell_concentration * diffusion_rate)
    out_diffusion = time_step * cell_concentration * diffusion_rate * 2

    updated_concentration = cell_concentration + in_diffusion - out_diffusion

    return updated_concentration


def update_lower_left_corner_concentration1(
    cell_concentration,
    upper_cell_concentration,
    right_cell_concentration,
    diffusion_rate,
    time_step):
    """
    Update the concentration of a species in a cell located at the lower-left corner of a 2D compartment
    based on diffusion from neighboring cells.

    Parameters:
    - cell_concentration (1d array): Concentration of the species in the lower-left corner cell.
    - upper_cell_concentration (1d array): Concentration of the species in the cell directly above the lower-left cell.
    - right_cell_concentration (1d array): Concentration of the species in the cell directly to the right of the lower-left cell.
    - diffusion_rate (float): Rate at which the species diffuses between cells.
    - time_step (float): Discrete time step for the calculation.

    Returns:
    - 1d array: Updated concentration of the species in the lower-left corner cell.
    """
    in_diffusion = (time_step * upper_cell_concentration * diffusion_rate) + \
                   (time_step * right_cell_concentration * diffusion_rate)
    out_diffusion = time_step * cell_concentration * diffusion_rate * 2

    updated_concentration = cell_concentration + in_diffusion - out_diffusion

    return updated_concentration

In [62]:
c1 = tf.fill(dims=(10, ), value=10.0)
uc1 = tf.fill(dims=(10, ), value=2.0)
rc1 = tf.fill(dims=(10, ), value=12.0)

c11 = np.full((10, ), fill_value=10.0)
uc11 = np.full((10, ), fill_value=2.0)
rc11 = np.full((10, ), fill_value=12.0)

In [65]:
tf_c = update_lower_left_corner_concentration1(c1, uc1, rc1, 0.4, 0.2)
np_c = update_lower_left_corner_concentration(c11, uc11, rc11, 0.4, 0.2)

In [66]:
np_c

array([9.52, 9.52, 9.52, 9.52, 9.52, 9.52, 9.52, 9.52, 9.52, 9.52])

In [67]:
tf_c

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([9.5199995, 9.5199995, 9.5199995, 9.5199995, 9.5199995, 9.5199995,
       9.5199995, 9.5199995, 9.5199995, 9.5199995], dtype=float32)>

In [78]:
c = tf.fill((10, ), 10.0)
b = tf.fill((8,), 9.0)

t = tf.tensor_scatter_nd_update(c, list([i] for i in range(1, 9)),b)
t
        

<tf.Tensor: shape=(10,), dtype=float32, numpy=array([10.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9., 10.], dtype=float32)>

In [84]:
j = tf.fill((10, ), -2.0)
h = tf.maximum(j, 0.0)

In [85]:
j

<tf.Tensor: shape=(10,), dtype=float32, numpy=array([-2., -2., -2., -2., -2., -2., -2., -2., -2., -2.], dtype=float32)>

In [86]:
h

<tf.Tensor: shape=(10,), dtype=float32, numpy=array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>

In [90]:
def update_lower_left_corner_concentration(
    cell_concentration,
    upper_cell_concentration,
    right_cell_concentration,
    diffusion_rate,
    time_step):
  
    in_diffusion = (time_step * upper_cell_concentration * diffusion_rate) + \
                   (time_step * right_cell_concentration * diffusion_rate)
    out_diffusion = time_step * cell_concentration * diffusion_rate * 2

    updated_concentration = cell_concentration + in_diffusion - out_diffusion

    return updated_concentration

h = tf.fill((10, ), 12.0)
h1 = tf.fill((10, ), 1.1)
h2 = tf.fill((10, ), 9.0)
h4 = update_lower_left_corner_concentration(h, h1, h2, 0.2, .05)
h4

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([11.861, 11.861, 11.861, 11.861, 11.861, 11.861, 11.861, 11.861,
       11.861, 11.861], dtype=float32)>

In [120]:

def update_central_concentration_lower(
        cell_concentration,
        upper_cell_concentration,
        right_cell_concentration,
        left_cell_concentration,
        diffusion_rate,
        time_step
):
 
    upper_cell_in = time_step * upper_cell_concentration * diffusion_rate
    right_cell_in = time_step * right_cell_concentration * diffusion_rate
    left_cell_in = time_step * left_cell_concentration * diffusion_rate

    in_diffusion = upper_cell_in + right_cell_in + left_cell_in
    out_diffusion = time_step * cell_concentration * diffusion_rate * 3

    updated_concentration = cell_concentration + in_diffusion - out_diffusion
    updated_concentration = tf.reshape(tensor=updated_concentration, shape=(1,))
    print(updated_concentration)

    return updated_concentration






current_concentration = tf.fill((10, ), value=10.0)

com = tf.fill((10, 10), value=0.0)
indices = tf.constant([[i, j] for i in range(10) for j in range(5, 7)])
updates = tf.constant([2.0] * 20)
com1 = tf.tensor_scatter_nd_update(com, indices, updates)
print(com1.shape)



d = tf.tensor_scatter_nd_update(tensor=current_concentration, indices=[[9]], updates=update_central_concentration_lower(
    cell_concentration=current_concentration[9],
    upper_cell_concentration=com1[-2, 5],
    right_cell_concentration=com1[-1, 5 + 1],
    left_cell_concentration=com1[-1, 5 - 1],
    diffusion_rate=0.2,
    time_step=0.1))
d

(10, 10)
tf.Tensor([9.48], shape=(1,), dtype=float32)


<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([10.  , 10.  , 10.  , 10.  , 10.  , 10.  , 10.  , 10.  , 10.  ,
        9.48], dtype=float32)>

In [110]:
import tensorflow as tf

def update_central_concentration_upper(
        cell_concentration,
        lower_cell_concentration,
        right_cell_concentration,
        left_cell_concentration,
        diffusion_rate,
        time_step
):
    lower_cell_in = time_step * lower_cell_concentration * diffusion_rate
    right_cell_in = time_step * right_cell_concentration * diffusion_rate
    left_cell_in = time_step * left_cell_concentration * diffusion_rate

    in_diffusion = lower_cell_in + right_cell_in + left_cell_in
    out_diffusion = time_step * cell_concentration * diffusion_rate * 3

    updated_concentration = cell_concentration + in_diffusion - out_diffusion

    return updated_concentration

# Initialize tensors
current_concentration = tf.fill((10,), value=10.0)
com = tf.fill((10, 10), value=0.0)

# Apply updates
indices = tf.constant([[i, j] for i in range(10) for j in range(5, 7)])
updates = tf.constant([2.0] * 20)
com1 = tf.tensor_scatter_nd_update(com, indices, updates)

# Call the update function and make sure it outputs a scalar
new_concentration_value = update_central_concentration_upper(
    cell_concentration=current_concentration[0].numpy(),  # Convert to numpy if needed
    lower_cell_concentration=com1[1, 5].numpy(),
    right_cell_concentration=com1[0, 6].numpy(),  # Correct column index
    left_cell_concentration=com1[0, 4].numpy(),   # Correct column index
    diffusion_rate=0.2,
    time_step=0.1
)

# Convert the scalar value to a tensor with the correct shape for updates
updates_tensor = tf.constant([new_concentration_value], dtype=tf.float32)

# Update the tensor
d = tf.tensor_scatter_nd_update(
    tensor=current_concentration,
    indices=[[0]],  # Indices for the update
    updates=updates_tensor  # Update values
)

print(d)


tf.Tensor([ 9.48 10.   10.   10.   10.   10.   10.   10.   10.   10.  ], shape=(10,), dtype=float32)


In [121]:
d.shape

TensorShape([10])

In [122]:
h = tf.fill((10, 10), 45.0)
h.shape[1]

10

In [9]:
params = {"sp1":tf.Variable([22.0, 32.0, 76.0]), "sp2": tf.Variable([32.0, 98.0, 34.0]), "sp3": tf.Variable([42.0, 1.0, 2.0])}


for j in range(0, 3*2, 2):
    print(params[f"sp{int((j/2) + 1)}"][0])

tf.Tensor(283.8, shape=(), dtype=float32)
tf.Tensor(412.8, shape=(), dtype=float32)
tf.Tensor(541.8, shape=(), dtype=float32)


In [16]:
num_sp = 3
pair_start = int(num_sp * 2)  # Starting index for species pairs
pair_stop = int(pair_start + (4 * 2))
pair_start

6

In [17]:
pair_stop

14

In [22]:
for i in range(pair_start, pair_stop-2, 2):
    print(params[f"sp{int(i/2 - num_sp+1)}"])

<tf.Variable 'Variable:0' shape=(3,) dtype=float32, numpy=array([22., 32., 76.], dtype=float32)>
<tf.Variable 'Variable:0' shape=(3,) dtype=float32, numpy=array([32., 98., 34.], dtype=float32)>
<tf.Variable 'Variable:0' shape=(3,) dtype=float32, numpy=array([42.,  1.,  2.], dtype=float32)>


In [24]:
p = {"q": tf.Variable([1,2,3]), "w": tf.Variable([3,5,6,7])}
h = list(p.values())
h

[<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3], dtype=int32)>,
 <tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([3, 5, 6, 7], dtype=int32)>]